2024-05-12 11:12:22,316 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Configure stats pid to 11460
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Loading settings from /home/woo/.config/wandb/settings
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Loading settings from /home/woo/gist/24_1/de/hw2/wandb/settings
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_init.py:_log_setup():520] Logging user logs to /home/woo/gist/24_1/de/hw2/wandb/run-20240512_111222-oq9iw9br/logs/debug.log
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_init.py:_log_setup():521] Logging internal logs to /home/woo/gist/24_1/de/hw2/wandb/run-20240512_111222-oq9iw9br/logs/debug-internal.log
2024-05-12 11:12:22,317 INFO    MainThread:11460 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f51ff74fcd0>
2024-05-12 11:12:22,318 INFO    MainThread:11460 [wandb_init.py:init():560] calling init triggers
2024-05-12 11:12:22,318 INFO    MainThread:11460 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-12 11:12:22,318 INFO    MainThread:11460 [wandb_init.py:init():610] starting backend
2024-05-12 11:12:22,318 INFO    MainThread:11460 [wandb_init.py:init():614] setting up manager
2024-05-12 11:12:22,323 INFO    MainThread:11460 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-12 11:12:22,324 INFO    MainThread:11460 [wandb_init.py:init():622] backend started and connected
2024-05-12 11:12:22,341 INFO    MainThread:11460 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-12 11:12:22,342 INFO    MainThread:11460 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-12 11:12:22,342 INFO    MainThread:11460 [wandb_init.py:init():711] updated telemetry
2024-05-12 11:12:22,402 INFO    MainThread:11460 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-12 11:12:23,147 ERROR   MainThread:11460 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-12 11:12:23,147 ERROR   MainThread:11460 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/home/woo/gist/24_1/de/hw2/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/woo/gist/24_1/de/hw2/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-12 11:33:55,954 INFO    MainThread:11460 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-12 11:33:55,966 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-12 11:33:55,966 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Configure stats pid to 11460
2024-05-12 11:33:55,966 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Loading settings from /home/woo/.config/wandb/settings
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Loading settings from /home/woo/gist/24_1/de/hw2/wandb/settings
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_init.py:_log_setup():520] Logging user logs to /home/woo/gist/24_1/de/hw2/wandb/run-20240512_113355-15z72hbk/logs/debug.log
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_init.py:_log_setup():521] Logging internal logs to /home/woo/gist/24_1/de/hw2/wandb/run-20240512_113355-15z72hbk/logs/debug-internal.log
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_init.py:init():560] calling init triggers
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_init.py:init():610] starting backend
2024-05-12 11:33:55,967 INFO    MainThread:11460 [wandb_init.py:init():614] setting up manager
2024-05-12 11:33:55,974 INFO    MainThread:11460 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-12 11:33:55,975 INFO    MainThread:11460 [wandb_init.py:init():622] backend started and connected
2024-05-12 11:33:56,008 INFO    MainThread:11460 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-12 11:33:56,009 INFO    MainThread:11460 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-12 11:33:56,009 INFO    MainThread:11460 [wandb_init.py:init():711] updated telemetry
2024-05-12 11:33:56,017 INFO    MainThread:11460 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-12 11:34:15,055 WARNING MainThread:11460 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/home/woo/gist/24_1/de/hw2/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/home/woo/gist/24_1/de/hw2/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 747, in init
    result = run_init_handle.wait(
  File "/home/woo/gist/24_1/de/hw2/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/woo/gist/24_1/de/hw2/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/woo/gist/24_1/de/hw2/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-05-12 11:34:22,128 INFO    MainThread:11460 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-12 22:50:22,183 INFO    MainThread:11460 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
